// Copyright (c) The Bitcoin Core developers
// Copyright (c) 2025-present The Elektron Net developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit.

#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Elektron Net network.
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 *
 * Elektron Net mainnet relies on DNS seeds (seed.elektron-net.org) instead of
 * hardcoded fixed seeds. Regenerate this file after adding fixed seeds.
 */
// MSVC rejects zero-length arrays; placeholder byte is unused (FixedSeeds are cleared in chainparams).
static const uint8_t chainparams_seed_main[] = {0};
static const uint8_t chainparams_seed_signet[] = {0};
static const uint8_t chainparams_seed_test[] = {0};
static const uint8_t chainparams_seed_testnet4[] = {0};
#endif // BITCOIN_CHAINPARAMSSEEDS_H